### ISSUE TITLE
[PE-D][Tester B] Non-functioning eclear command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#173] opened 2023-11-03 20:37 UTC
![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/ee634b7f-3a99-4c39-9d32-eae064b2186a.png)

![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/51617fc1-7c63-4367-a692-ed96d42ee10b.png)

`eclear` command stated in UG but not functioning.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Gavino3o/ped#9

**Comment by brein62** [comment] 2023-11-04 10:42
Duplicate of #191.

**Closed by brein62** 2023-11-04 10:42 UTC
Labels: duplicate
