### ISSUE TITLE
[PE-D][Tester B] Unable to add events

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#151] opened 2023-11-03 18:35 UTC
Input:
`ecreate n/clean beach r/cleaner sd/30/11/2023 1200 ed/30/11/2023 1800 l/east coast park dsc/help clean east coast park m/10 pairs of gloves m/10 trash bags b/50.00`

note: Input is taken from UG

Expected: 
An event with name clean beach, roles needed cleaner, event date from 30th November 2023, 12pm to 30th November 2023, 6pm, location east coast park, description help clean east coast park, materials needed 10 pairs of gloves and 10 trash bags and budget $50.00 to be created.

Actual:
No event added, no command result when pressing "Enter" key.

![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/24605198-eb68-4e14-816f-933b26b467fb.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Gavino3o/ped#3

**Comment by brein62** [comment] 2023-11-04 11:08
Same issue as #154 and fixed in #141. Issue is a duplicate of #143

**Closed by brein62** 2023-11-04 11:08 UTC
Labels: duplicate
