### ISSUE TITLE
[PE-D][Tester B] Invalid command example for vdelete in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#177] opened 2023-11-03 21:09 UTC
![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/8e3fa869-339a-4c12-ba40-6fb9d89c51a8.png)

Invalid command provided in command example

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Gavino3o/ped#11

**Comment by brein62** [comment] 2023-11-04 10:47
Duplicate of #186.

**Closed by brein62** 2023-11-04 10:47 UTC
